import { describe, it, expect } from 'vitest';
import { exportSvg } from '../../src/modules/exporter/svg-export';
import { makeMinimalResult, makeStandardResult } from '../fixtures/fretboard-result';
import type { ExportOptions } from '../../src/modules/exporter/types';

const MINIMAL = makeMinimalResult();
const STANDARD = makeStandardResult();

function opts(overrides?: Partial<ExportOptions>): ExportOptions {
  return { format: 'svg', unit: 'mm', annotations: true, ...overrides };
}

describe('exporter/svg-export', () => {
  it('output starts with <?xml', () => {
    const svg = exportSvg(MINIMAL, opts());
    expect(svg.startsWith('<?xml')).toBe(true);
  });

  it('includes <svg> tag with width and height in correct unit', () => {
    const svg = exportSvg(MINIMAL, opts({ unit: 'mm' }));
    expect(svg).toContain('<svg');
    expect(svg).toContain('width="');
    expect(svg).toContain('height="');
    expect(svg).toContain('mm"');
  });

  it('includes <svg> tag with cm unit suffix', () => {
    const svg = exportSvg(MINIMAL, opts({ unit: 'cm' }));
    expect(svg).toContain('cm"');
  });

  it('includes <svg> tag with in unit suffix', () => {
    const svg = exportSvg(MINIMAL, opts({ unit: 'in' }));
    expect(svg).toContain('in"');
  });

  it('includes viewBox attribute', () => {
    const svg = exportSvg(MINIMAL, opts());
    expect(svg).toContain('viewBox="');
  });

  it('includes background <rect>', () => {
    const svg = exportSvg(MINIMAL, opts());
    expect(svg).toContain('<rect');
    expect(svg).toContain('fill="#FFFFFF"');
  });

  it('includes fretboard fill <path>', () => {
    const svg = exportSvg(MINIMAL, opts());
    expect(svg).toContain('<path');
    expect(svg).toContain('fill="#F5EFE0"');
  });

  describe('fret lines', () => {
    it('includes line elements for frets', () => {
      const svg = exportSvg(MINIMAL, opts());
      const lines = svg.split('\n').filter((l) => l.trim().startsWith('<line'));
      expect(lines.length).toBeGreaterThanOrEqual(2);
    });

    it('nut (fret 0) has thicker stroke than other frets', () => {
      const svg = exportSvg(MINIMAL, opts());
      const nutLines = svg.split('\n').filter((l) => l.includes('stroke-width="2.5"'));
      expect(nutLines.length).toBeGreaterThanOrEqual(1);
      const fretLines = svg.split('\n').filter((l) => l.includes('stroke-width="0.6"'));
      expect(fretLines.length).toBeGreaterThanOrEqual(1);
    });

    it('includes string lines', () => {
      const svg = exportSvg(MINIMAL, opts());
      const stringLines = svg.split('\n').filter((l) => l.includes('stroke-opacity="0.75"'));
      expect(stringLines.length).toBe(2);
    });
  });

  describe('annotations', () => {
    it('includes annotation elements when annotations=true', () => {
      const svg = exportSvg(STANDARD, opts({ annotations: true }));
      expect(svg).toContain('Scale:');
      expect(svg).toContain('</text>');
    });

    it('omits annotation elements when annotations=false', () => {
      const svg = exportSvg(STANDARD, opts({ annotations: false }));
      expect(svg).not.toContain('Scale:');
    });

    it('includes fret markers for fret 12', () => {
      const svg = exportSvg(STANDARD, opts());
      expect(svg).toContain('>12<');
    });

    it('includes fret markers for fret 24', () => {
      const svg = exportSvg(STANDARD, opts());
      expect(svg).toContain('>24<');
    });
  });

  describe('metadata comment', () => {
    it('includes Generated by FretLabs comment', () => {
      const svg = exportSvg(MINIMAL, opts());
      expect(svg).toContain('Generated by FretLabs');
    });

    it('documents equal temperament in comment', () => {
      const svg = exportSvg(MINIMAL, opts());
      expect(svg).toContain('Equal Temperament');
    });

    it('documents scala method in comment', () => {
      const scalaResult = makeMinimalResult({
        meta: { method: 'scala', tonesPerOctave: 12, scalaDescription: 'Just intonation', inputUnit: 'mm' },
      });
      const svg = exportSvg(scalaResult, opts());
      expect(svg).toContain('Scala');
      expect(svg).toContain('Just intonation');
    });
  });
});
