/**
 * "PDF" export — implemented as a print-ready, tiled HTML document.
 *
 * It embeds the physically-sized SVG and partitions it dynamically
 * across standard paper sizes (A4 or Letter) with alignment marks
 * and overlap regions so that luthiers can print at 100% scale
 * on common printers and assemble the sheets with micron precision.
 */

import type { FretboardResult } from '../calculator/types';
import type { ExportOptions } from './types';
import { exportSvg } from './svg-export';
import en from '../../i18n/en.json';
import es from '../../i18n/es.json';

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

export function exportPdfHtml(result: FretboardResult, options: ExportOptions): string {
  const svgRaw = exportSvg(result, { ...options, format: 'svg', annotations: true });
  // Clean XML declaration and comments before the <svg tag for HTML5 compatibility
  const svgStartIdx = svgRaw.indexOf('<svg');
  const svg = svgStartIdx !== -1 ? svgRaw.slice(svgStartIdx) : svgRaw;

  const method =
    result.meta.method === 'equal'
      ? `Equal (${result.meta.tonesPerOctave ?? 12} TPO)`
      : `Scala (${result.meta.scalaDescription ?? 'custom'})`;

  const caption = `FretLabs | ${method} | Unit: ${options.unit} | Print at 100% scale`;

  const locale = options.locale === 'es' ? 'es' : 'en';

  const _ = (key: string): string => {
    const dict = locale === 'es' ? es : en;
    return (dict as Record<string, string>)[`export.pdf.${key}`] ?? key;
  };

  return [
    '<!doctype html>',
    '<html lang="' + locale + '">',
    '<head>',
    '  <meta charset="utf-8" />',
    '  <meta name="viewport" content="width=device-width, initial-scale=1" />',
    `        <title>${escapeHtml(_('title'))}</title>`,
    '  <link rel="preconnect" href="https://fonts.googleapis.com">',
    '  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>',
    '  <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@400;500;600;700&display=swap" rel="stylesheet">',
    '  <style>',
    '    body {',
    '      margin: 0;',
    '      background-color: #f1f5f9;',
    '      font-family: "Outfit", system-ui, -apple-system, sans-serif;',
    '      color: #0f172a;',
    '      -webkit-print-color-adjust: exact;',
    '      print-color-adjust: exact;',
    '    }',
    '    .toolbar {',
    '      background: rgba(15, 23, 42, 0.95);',
    '      backdrop-filter: blur(12px);',
    '      -webkit-backdrop-filter: blur(12px);',
    '      color: #fff;',
    '      padding: 14px 28px;',
    '      display: flex;',
    '      flex-direction: row;',
    '      align-items: center;',
    '      justify-content: space-between;',
    '      gap: 24px;',
    '      position: sticky;',
    '      top: 0;',
    '      z-index: 1000;',
    '      box-shadow: 0 4px 20px rgba(0, 0, 0, 0.15);',
    '      border-bottom: 1px solid rgba(255, 255, 255, 0.08);',
    '    }',
    '    .toolbar h1 {',
    '      margin: 0;',
    '      font-size: 18px;',
    '      font-weight: 600;',
    '      letter-spacing: -0.025em;',
    '      background: linear-gradient(135deg, #3b82f6, #60a5fa);',
    '      -webkit-background-clip: text;',
    '      -webkit-text-fill-color: transparent;',
    '    }',
    '    .toolbar-controls {',
    '      display: flex;',
    '      align-items: center;',
    '      gap: 20px;',
    '    }',
    '    .select-wrapper {',
    '      display: flex;',
    '      align-items: center;',
    '      gap: 8px;',
    '      font-size: 14px;',
    '      color: #94a3b8;',
    '    }',
    '    .toolbar-select {',
    '      background-color: #1e293b;',
    '      color: #f8fafc;',
    '      border: 1px solid #334155;',
    '      padding: 8px 16px;',
    '      border-radius: 8px;',
    '      font-family: inherit;',
    '      font-size: 14px;',
    '      font-weight: 500;',
    '      cursor: pointer;',
    '      outline: none;',
    '      transition: border-color 0.2s, box-shadow 0.2s;',
    '    }',
    '    .toolbar-select:focus {',
    '      border-color: #3b82f6;',
    '      box-shadow: 0 0 0 2px rgba(59, 130, 246, 0.3);',
    '    }',
    '    .instructions {',
    '      background: rgba(245, 158, 11, 0.1);',
    '      border: 1px dashed rgba(245, 158, 11, 0.3);',
    '      padding: 8px 16px;',
    '      border-radius: 8px;',
    '      max-width: 600px;',
    '      font-size: 12px;',
    '      line-height: 1.5;',
    '      color: #f59e0b;',
    '    }',
    '    .instructions strong {',
    '      color: #fbbf24;',
    '    }',
    '    .toolbar-buttons {',
    '      display: flex;',
    '      gap: 12px;',
    '    }',
    '    .btn {',
    '      font-family: inherit;',
    '      font-size: 14px;',
    '      font-weight: 600;',
    '      padding: 10px 20px;',
    '      border-radius: 8px;',
    '      cursor: pointer;',
    '      border: none;',
    '      transition: transform 0.15s, background-color 0.15s, box-shadow 0.15s;',
    '    }',
    '    .btn:active {',
    '      transform: scale(0.97);',
    '    }',
    '    .btn-primary {',
    '      background: linear-gradient(135deg, #2563eb, #3b82f6);',
    '      color: #fff;',
    '      box-shadow: 0 4px 12px rgba(37, 99, 235, 0.2);',
    '    }',
    '    .btn-primary:hover {',
    '      background: linear-gradient(135deg, #1d4ed8, #2563eb);',
    '      box-shadow: 0 4px 16px rgba(37, 99, 235, 0.3);',
    '    }',
    '    .btn-secondary {',
    '      background-color: #334155;',
    '      color: #f8fafc;',
    '    }',
    '    .btn-secondary:hover {',
    '      background-color: #475569;',
    '    }',
    '    .pages-container {',
    '      display: flex;',
    '      flex-direction: row;',
    '      padding: 40px;',
    '      gap: 40px;',
    '      overflow-x: auto;',
    '      justify-content: flex-start;',
    '      align-items: center;',
    '      min-height: calc(100vh - 120px);',
    '      scroll-behavior: smooth;',
    '    }',
    '    .page {',
    '      background-color: #fff;',
    '      box-shadow: 0 12px 36px rgba(0, 0, 0, 0.08), 0 4px 12px rgba(0, 0, 0, 0.03);',
    '      border-radius: 12px;',
    '      box-sizing: border-box;',
    '      position: relative;',
    '      flex-shrink: 0;',
    '      display: flex;',
    '      flex-direction: column;',
    '      justify-content: center;',
    '      align-items: center;',
    '      transition: transform 0.3s, box-shadow 0.3s;',
    '    }',
    '    .page:hover {',
    '      transform: translateY(-4px);',
    '      box-shadow: 0 16px 48px rgba(0, 0, 0, 0.12), 0 6px 16px rgba(0, 0, 0, 0.05);',
    '    }',
    '    .page-info {',
    '      position: absolute;',
    '      top: 15px;',
    '      left: 20px;',
    '      font-size: 12px;',
    '      font-weight: 600;',
    '      color: #64748b;',
    '      background: #f1f5f9;',
    '      padding: 4px 10px;',
    '      border-radius: 6px;',
    '      letter-spacing: 0.025em;',
    '    }',
    '    .page-inner {',
    '      border: 1px dashed #cbd5e1;',
    '      border-radius: 8px;',
    '      position: relative;',
    '      box-sizing: border-box;',
    '      display: flex;',
    '      align-items: center;',
    '      justify-content: flex-start;',
    '      overflow: hidden;',
    '      background-color: #fff;',
    '    }',
    '    .page-inner svg {',
    '      position: absolute;',
    '      top: 50%;',
    '      left: 0;',
    '      transform: translateY(-50%);',
    '      display: block;',
    '    }',
    '    .align-line {',
    '      position: absolute;',
    '      top: 0;',
    '      bottom: 0;',
    '      border-left: 1px dashed #10b981;',
    '      width: 0;',
    '      z-index: 100;',
    '    }',
    '    .align-label {',
    '      position: absolute;',
    '      top: 25mm;',
    '      left: 3px;',
    '      font-family: monospace;',
    '      font-size: 8px;',
    '      font-weight: bold;',
    '      color: #059669;',
    '      transform: rotate(90deg);',
    '      transform-origin: left top;',
    '      white-space: nowrap;',
    '      letter-spacing: 0.05em;',
    '    }',
    '    .cut-line {',
    '      position: absolute;',
    '      top: 0;',
    '      bottom: 0;',
    '      border-left: 1px dashed #f43f5e;',
    '      width: 0;',
    '      z-index: 100;',
    '    }',
    '    .cut-label {',
    '      position: absolute;',
    '      top: 25mm;',
    '      left: 3px;',
    '      font-family: monospace;',
    '      font-size: 8px;',
    '      font-weight: bold;',
    '      color: #e11d48;',
    '      transform: rotate(90deg);',
    '      transform-origin: left top;',
    '      white-space: nowrap;',
    '      letter-spacing: 0.05em;',
    '    }',
    '    .reg-mark {',
    '      position: absolute;',
    '      left: -8px;',
    '      font-size: 15px;',
    '      font-weight: bold;',
    '      width: 16px;',
    '      height: 16px;',
    '      line-height: 16px;',
    '      text-align: center;',
    '      background: #fff;',
    '      border-radius: 50%;',
    '      box-shadow: 0 0 2px rgba(0, 0, 0, 0.2);',
    '    }',
    '    .reg-mark-top {',
    '      top: 15mm;',
    '      color: inherit;',
    '    }',
    '    .reg-mark-bottom {',
    '      bottom: 15mm;',
    '      color: inherit;',
    '    }',
    '    @media print {',
    '      body {',
    '        background-color: #fff;',
    '        padding: 0;',
    '        margin: 0;',
    '      }',
    '      .no-print {',
    '        display: none !important;',
    '      }',
    '      .pages-container {',
    '        padding: 0;',
    '        margin: 0;',
    '        gap: 0;',
    '        display: block;',
    '        overflow-x: visible;',
    '        min-height: auto;',
    '      }',
    '      .page {',
    '        box-shadow: none;',
    '        margin: 0;',
    '        border: none;',
    '        border-radius: 0;',
    '        transform: none !important;',
    '        page-break-after: always;',
    '        width: var(--page-width) !important;',
    '        height: var(--page-height) !important;',
    '      }',
    '      .page-inner {',
    '        border: none;',
    '        border-radius: 0;',
    '        margin: var(--page-margin) !important;',
    '        width: calc(var(--page-width) - (var(--page-margin) * 2)) !important;',
    '        height: calc(var(--page-height) - (var(--page-margin) * 2)) !important;',
    '      }',
    '    }',
    '  </style>',
    '</head>',
    '<body>',
    '  <header class="toolbar no-print">',
    '    <div style="display: flex; flex-direction: column; gap: 4px;">',
    `      <h1>${escapeHtml(_('title'))}</h1>`,
    `      <div style="font-size: 11px; color: #94a3b8;">${escapeHtml(caption)}</div>`,
    '    </div>',
    '    <div class="toolbar-controls">',
    '      <div class="select-wrapper">',
    `        <label for="paper-select">${escapeHtml(_('paperSize'))}</label>`,
    '        <select id="paper-select" class="toolbar-select">',
    '          <option value="a4" selected>A4 Landscape (297 x 210 mm)</option>',
    '          <option value="letter">Letter Landscape (279.4 x 215.9 mm)</option>',
    '        </select>',
    '      </div>',
    `      <div class="instructions">${_('instructionsText')}</div>`,
    '      <div class="toolbar-buttons">',
    `        <button class="btn btn-secondary" onclick="window.close()">${escapeHtml(_('close'))}</button>`,
    `        <button class="btn btn-primary" onclick="window.print()">${escapeHtml(_('print'))}</button>`,
    '      </div>',
    '    </div>',
    '  </header>',
    '  <main class="pages-container" id="pages-container">',
    '    <!-- Pages will be rendered here dynamically by JS -->',
    '  </main>',
    '  <div id="original-svg" style="display: none;">',
    svg,
    '  </div>',
    '  <script>',
    '    const strings = ' + JSON.stringify({pageOf:_('pageOf'),cutHere:_('cutHere'),alignHere:_('alignHere')}) + ';',
    '    const svgEl = document.querySelector("#original-svg svg");',
    '    const viewBoxStr = svgEl.getAttribute("viewBox");',
    '    const [minX, minY, widthMm, heightMm] = viewBoxStr.split(/\\s+/).map(Number);',
    '    const maxX = minX + widthMm;',
    '',
    '    function renderPages() {',
    '      const paperType = document.getElementById("paper-select").value;',
    '      let paperWidth, paperHeight;',
    '      if (paperType === "a4") {',
    '        paperWidth = 297;',
    '        paperHeight = 210;',
    '      } else {',
    '        paperWidth = 279.4;',
    '        paperHeight = 215.9;',
    '      }',
    '',
    '      const margin = 10; // 10mm margins',
    '      const overlap = 20; // 20mm overlap',
    '',
    '      const W_util = paperWidth - (margin * 2);',
    '      const H_util = paperHeight - (margin * 2);',
    '      const W_step = W_util - overlap;',
    '',
    '      let N = 1;',
    '      if (widthMm > W_util) {',
    '        N = 1 + Math.ceil((widthMm - W_util) / W_step);',
    '      }',
    '',
    '      // Inject dynamic page CSS sizes',
    '      const styleId = "dynamic-page-style";',
    '      let styleEl = document.getElementById(styleId);',
    '      if (!styleEl) {',
    '        styleEl = document.createElement("style");',
    '        styleEl.id = styleId;',
    '        document.head.appendChild(styleEl);',
    '      }',
    '      styleEl.innerHTML = `',
    '        @page {',
    '          size: ${paperType === "a4" ? "A4" : "letter"} landscape;',
    '          margin: 0;',
    '        }',
    '        :root {',
    '          --page-width: ${paperWidth}mm;',
    '          --page-height: ${paperHeight}mm;',
    '          --page-margin: ${margin}mm;',
    '        }',
    '      `;',
    '',
    '      const container = document.getElementById("pages-container");',
    '      container.innerHTML = "";',
    '',
    '      for (let i = 0; i < N; i++) {',
    '        const X_start = minX + i * W_step;',
    '        const W_viewbox = Math.min(W_util, maxX - X_start);',
    '',
    '        const pageDiv = document.createElement("div");',
    '        pageDiv.className = "page";',
    '        pageDiv.style.width = paperWidth + "mm";',
    '        pageDiv.style.height = paperHeight + "mm";',
    '',
    '        const pageInfo = document.createElement("div");',
    '        pageInfo.className = "page-info no-print";',
    '        pageInfo.textContent = strings.pageOf.replace("{current}", i + 1).replace("{total}", N);',
    '        pageDiv.appendChild(pageInfo);',
    '',
    '        const innerDiv = document.createElement("div");',
    '        innerDiv.className = "page-inner";',
    '        innerDiv.style.width = W_util + "mm";',
    '        innerDiv.style.height = H_util + "mm";',
    '        innerDiv.style.margin = margin + "mm";',
    '        const svgClone = svgEl.cloneNode(true);',
    '        svgClone.style.display = "";',
    '        svgClone.setAttribute("width", W_viewbox + "mm");',
    '        svgClone.setAttribute("height", heightMm + "mm");',
    '        svgClone.setAttribute("viewBox", X_start + " " + minY + " " + W_viewbox + " " + heightMm);',
    '        innerDiv.appendChild(svgClone);',
    '',
    '        if (i > 0) {',
    '          const alignLine = document.createElement("div");',
    '          alignLine.className = "align-line";',
    '          alignLine.style.left = "0px";',
    '          alignLine.innerHTML = `',
    '            <span class="align-label">${strings.alignHere.replace("{prev}", i)}</span>',
    '            <span class="reg-mark reg-mark-top">⊕</span>',
    '            <span class="reg-mark reg-mark-bottom">⊕</span>',
    '          `;',
    '          innerDiv.appendChild(alignLine);',
    '        }',
    '',
    '        if (i < N - 1) {',
    '          const cutLine = document.createElement("div");',
    '          cutLine.className = "cut-line";',
    '          cutLine.style.left = W_step + "mm";',
    '          cutLine.innerHTML = `',
    '            <span class="cut-label">${strings.cutHere.replace("{next}", i + 2)}</span>',
    '            <span class="reg-mark reg-mark-top">⊕</span>',
    '            <span class="reg-mark reg-mark-bottom">⊕</span>',
    '          `;',
    '          innerDiv.appendChild(cutLine);',
    '        }',
    '',
    '        pageDiv.appendChild(innerDiv);',
    '        container.appendChild(pageDiv);',
    '      }',
    '    }',
    '',
    '    document.getElementById("paper-select").addEventListener("change", renderPages);',
    '    renderPages();',
    '    setTimeout(() => {',
    '      try { window.focus(); } catch {}',
    '      try { window.print(); } catch {}',
    '    }, 500);',
    '  </script>',
    '</body>',
    '</html>',
  ].join('\n');
}
