/**
 * SVG export — generates a standalone, physically-sized SVG string.
 *
 * The exported file uses a white background and is intended as a
 * design / reference document suitable for Inkscape, Illustrator,
 * or direct laser cutter import. Coordinates are kept in mm (the
 * internal unit) regardless of ExportOptions.unit; the width/height
 * attributes are expressed in the chosen unit so the file opens at
 * the correct physical size in CAD applications.
 *
 * Visual layers (bottom to top):
 *   1. White background rect
 *   2. Fretboard fill (light tan wood)
 *   3. Fret lines (nut is thicker)
 *   4. String lines
 *   5. Fretboard outline stroke
 */

import type { FretboardResult } from '../calculator/types';
import type { ExportOptions } from './types';
import { fromMm } from '../../utils/unit-converter';
import { extendSegmentToOutline } from '../../utils/extend-line-to-outline';

// ── Visual constants (light / print-friendly palette) ──────────────────────

const COLOR_BACKGROUND = '#FFFFFF';
const COLOR_BOARD_FILL = '#F5EFE0';
const COLOR_BOARD_EDGE = '#1A1A1A';
const COLOR_FRET = '#2A2A2A';
const COLOR_NUT = '#1A1A1A';
const COLOR_STRING = '#888888';

const STROKE_FRET_MM = 0.6;
const STROKE_NUT_MM = 2.5;
const STROKE_STRING_MM = 0.35;
const STROKE_BOARD_EDGE_MM = 0.8;

const SVG_PADDING_MM = 10;

/** Format a number to 4 decimal places for SVG coordinates */
function f(n: number): string {
  return n.toFixed(4);
}

/**
 * Generate a standalone SVG string from a fretboard calculation.
 *
 * @param result - Complete fretboard calculation result
 * @param options - Export options (unit is used for the width/height attributes)
 * @returns Complete SVG file content as a string
 */
export function exportSvg(result: FretboardResult, options: ExportOptions): string {
  const { unit } = options;
  const { fretLines, strings: stringLines, outline } = result;
  const extendFrets = options.extendFrets === true;

  // ── Compute bounding box and viewBox (all in mm) ──────────────────────────

  const xs = [
    outline.nutFirst.x,
    outline.nutLast.x,
    outline.bridgeFirst.x,
    outline.bridgeLast.x,
  ];
  const ys = [
    outline.nutFirst.y,
    outline.nutLast.y,
    outline.bridgeFirst.y,
    outline.bridgeLast.y,
  ];

  const minX = Math.min(...xs) - SVG_PADDING_MM;
  const minY = Math.min(...ys) - SVG_PADDING_MM;
  const maxX = Math.max(...xs) + SVG_PADDING_MM;
  const maxY = Math.max(...ys) + SVG_PADDING_MM;
  const widthMm = maxX - minX;
  const heightMm = maxY - minY;

  // Physical dimensions in the chosen unit (for width/height attributes)
  const widthDisplay = fromMm(widthMm, unit).toFixed(4);
  const heightDisplay = fromMm(heightMm, unit).toFixed(4);

  const viewBox = `${f(minX)} ${f(minY)} ${f(widthMm)} ${f(heightMm)}`;

  // ── Outline path (closed quadrilateral) ──────────────────────────────────

  const boardPath = [
    `M ${f(outline.nutFirst.x)} ${f(outline.nutFirst.y)}`,
    `L ${f(outline.nutLast.x)} ${f(outline.nutLast.y)}`,
    `L ${f(outline.bridgeLast.x)} ${f(outline.bridgeLast.y)}`,
    `L ${f(outline.bridgeFirst.x)} ${f(outline.bridgeFirst.y)}`,
    'Z',
  ].join(' ');

  // ── Build SVG sections ────────────────────────────────────────────────────

  // Background
  const background = `  <rect x="${f(minX)}" y="${f(minY)}" width="${f(widthMm)}" height="${f(heightMm)}" fill="${COLOR_BACKGROUND}"/>`;

  // Fretboard fill
  const boardFill = `  <path d="${boardPath}" fill="${COLOR_BOARD_FILL}"/>`;

  // Fret lines
  const fretSvgLines = fretLines.map((fl) => {
    const isNut = fl.fret === 0;
    const stroke = isNut ? COLOR_NUT : COLOR_FRET;
    const strokeWidth = isNut ? STROKE_NUT_MM : STROKE_FRET_MM;
    const seg = extendFrets
      ? extendSegmentToOutline(fl.x1, fl.y1, fl.x2, fl.y2, outline)
      : { x1: fl.x1, y1: fl.y1, x2: fl.x2, y2: fl.y2 };
    return `  <line x1="${f(seg.x1)}" y1="${f(seg.y1)}" x2="${f(seg.x2)}" y2="${f(seg.y2)}" stroke="${stroke}" stroke-width="${strokeWidth}" stroke-linecap="round"/>`;
  }).join('\n');

  // String lines
  const stringSvgLines = stringLines.map((sl) =>
    `  <line x1="${f(sl.nutX)}" y1="${f(sl.nutY)}" x2="${f(sl.bridgeX)}" y2="${f(sl.bridgeY)}" stroke="${COLOR_STRING}" stroke-width="${STROKE_STRING_MM}" stroke-opacity="0.75"/>`,
  ).join('\n');

  // Outline stroke
  const boardStroke = `  <path d="${boardPath}" fill="none" stroke="${COLOR_BOARD_EDGE}" stroke-width="${STROKE_BOARD_EDGE_MM}" stroke-linejoin="round"/>`;

  // ── Assemble metadata comment ─────────────────────────────────────────────

  const method = result.meta.method === 'equal'
    ? `Equal Temperament (${result.meta.tonesPerOctave ?? 12} tones/octave)`
    : `Scala — ${result.meta.scalaDescription ?? 'custom'}`;

  const numStrings = stringLines.length;
  const fretsPerString = Math.floor(result.fretPositions.length / Math.max(1, numStrings));
  const numFrets = Math.max(0, fretsPerString - 1);

  const comment = [
    `Generated by FretLabs`,
    `Method: ${method}`,
    `Frets: ${numFrets} | Strings: ${numStrings}`,
    `Coordinates in mm | Physical size in ${unit}`,
  ].map((l) => `  ${l}`).join('\n');

  // ── Final SVG ─────────────────────────────────────────────────────────────

  return [
    `<?xml version="1.0" encoding="UTF-8"?>`,
    `<!--`,
    comment,
    `-->`,
    `<svg`,
    `  xmlns="http://www.w3.org/2000/svg"`,
    `  width="${widthDisplay}${unit}"`,
    `  height="${heightDisplay}${unit}"`,
    `  viewBox="${viewBox}"`,
    `>`,
    background,
    boardFill,
    fretSvgLines,
    stringSvgLines,
    boardStroke,
    `</svg>`,
  ].join('\n');
}
